# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180717_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopingcart',
            old_name='goods_num',
            new_name='nums',
        ),
    ]
