# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180717_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='singer_name',
            new_name='signer_name',
        ),
    ]
